name: Infracost action
description: Cloud cost estimate for Terraform resource changes

inputs:
  environment:
    description: The environment to use, i.e. "production".
    required: true
  github-ssh-key:
    description: An SSH private key with access to clone private module repos.
    required: true
  infracost-api-key:
    description: The Infracost API Key.
    required: true
  region:
    description: The AWS region to use.
    required: true
  role-arn:
    description: An AWS role ARN that will be assumed for operations.
    required: true
  workspace:
    description: The Terraform workspace to use.
    required: true

runs:
  using: "composite"
  steps:
    - uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ inputs.github-ssh-key }}
    - name: Setup Infracost
      uses: infracost/actions/setup@v2
      with:
        api-key: ${{ inputs.infracost-api-key }}
    - name: Assume AWS role
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: ${{ inputs.region }}
        role-to-assume: ${{ inputs.role-arn }}
    - name: Setup SOPS
      uses: mdgreenwald/mozilla-sops-action@v1.2.0
    - name: Checkout base branch
      uses: actions/checkout@v2
      with:
        ref: '${{ github.event.pull_request.base.ref }}'
    - name: Decrypt sops secrets
      shell: bash
      run: |
        if [ -f "environments/${{ inputs.environment }}.secret.tfvars" ]; then
          sops -i -d "environments/${{ inputs.environment }}.secret.tfvars"
        fi
    - name: Generate Infracost cost estimate baseline
      shell: bash
      env:
        TF_ROOT: ${{ inputs.workspace }}
      run: |
        args=("breakdown"
          "--path=${TF_ROOT}"
          "--project-name=${{ inputs.environment }}-${{ inputs.workspace }}"
          "--format=json"
          "--out-file=/tmp/infracost-base.json"
          "--terraform-var-file=environments/${{ inputs.environment }}.tfvars"
        )
        test -f "environments/${{ inputs.environment }}.secret.tfvars" && args+=("--terraform-var-file=environments/${{ inputs.environment }}.secret.tfvars")

        echo "Running infracost ${args[@]}"
        infracost "${args[@]}"
    - name: Checkout PR branch
      uses: actions/checkout@v2
    - name: Generate Infracost diff
      shell: bash
      env:
        TF_ROOT: ${{ inputs.workspace }}
      run: |
        args=("diff"
          "--path=${TF_ROOT}"
          "--project-name=${{ inputs.environment }}-${{ inputs.workspace }}"
          "--format=json"
          "--compare-to=/tmp/infracost-base.json"
          "--out-file=/tmp/infracost.json"
          "--terraform-var-file=environments/${{ inputs.environment }}.tfvars"
        )
        test -f "environments/${{ inputs.environment }}.secret.tfvars" && args+=("--terraform-var-file=environments/${{ inputs.environment }}.secret.tfvars")
        echo "Running infracost ${args[@]}"
        infracost "${args[@]}"
    - name: Post Infracost comment
      shell: bash
      run: |
        infracost comment github --path=/tmp/infracost.json \
                                 --repo=$GITHUB_REPOSITORY \
                                 --github-token=${{github.token}} \
                                 --pull-request=${{github.event.pull_request.number}} \
                                 --behavior=update \
                                 --tag=infracost-${{ inputs.environment }}-${{ inputs.workspace }}

